// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let rawUrl = (
  process.env["DIRECT_URL"] || 
  process.env["SUPABASE_DIRECT_URL"] || 
  process.env["POSTGRES_URL_NON_POOLING"] || 
  process.env["DATABASE_URL"] || 
  ''
).replace(/\?sslmode=require|&sslmode=require/, '');

if (rawUrl.includes(':6543')) {
  console.log('[PrismaConfig] Converting Supabase pooler port 6543 (Transaction mode) -> 5432 (Session mode for migrations)');
  rawUrl = rawUrl.replace(':6543', ':5432');
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: rawUrl,
  },
});
